[logger]
level = "DEBUG"
file = "logs/logrus.log"

[HTTPServer]
host = "localhost"
port = "8081"

[gRPCServer]
host = "localhost"
port = "50051"

[DB]
enable = true
user = "root"
password = "12345"
host = "127.0.0.1"
port = "5432"
nameDB = "calendar"
